# Generated by Django 3.2.12 on 2022-05-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20220521_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
